= Designing a new structure for this game

== Installation

Download this repo with:

`git clone [this repo]`

== Usage

Play the game with:

`bin/play`

OR

`ruby bin/play`

== CRC design

                                         STORAGE CLASS
       +------------------+           +------------------+          +------------------+
       |      GAME        |           |      BOARD       |          |      PLAYER      |
       +------------------+           +------------------+          +------------------+
       |                  |           |* responsible for |          |* responsible     |
       |                  |           | keeping track    |          |  for providing   |
       |                  <|---------+| of plays on      |          |  location for    |
       |* says which      |           | board            |          |  move            |
       |  players turn    |           |                  |          |                  |
       |  it is           |           |                  |          |                  |
       |* maintains rules |           |                  <|---------+                  |
       |                  |           |                  |          |                  |
       +----.--------+----+           +------------------+          +---.--------------+
           /_\       |                                                 /_\ 
            |        +--------------------------------------------------+
            |
            +------------------------+
                                     |
                 SCRIPT              |
         \\\\\\\\\\\\\\\\\\\\\\\     |
         \ +---------------------+   |
         \ |+-------------------+|   |
         \ || * responsible for ||   |
         \ ||   prompt          ||   |
         \ ||   and input       |+---+
         \ ||                   ||
            +-------------------+


---- ✂  Snip Snip  ✂  ----

[source, ruby]
----
def start
  instructions<1>
  unless game_over <1>
    board.display<4>
    current_player.get_move<3>
    if move-checker redo<2>
    place(current_player.move, current_player.marker)<1>
      switchPlayers<1>
  end
end
----
<1> # GAME CLASS
<2> # BOARD CLASS
<3> # PLAYER CLASS
<4> # REPORT CLASS

== DRAFT_NOTES

.Option_1
[source, ruby]
----
def switch_player
  board.set_up.index[!false].length % 2 ? current_player = player_1
end
----
not this one

.Option_2
[source, ruby]
----
@current_player == player_1 ? @current_player = player_2 : @current_player = player_1
----

----
def initialize
end

public

def toggle_player
  @current_player = @current_player == player_2 ? player_1 : player_2
end
----

The board should not know anything about the player
