module Moves

  WINNING_MOVES = [
    'X','X','X',
    false,false,false,
    false,false,false],
    [
    false,false,false,
    'X','X','X',
    false,false,false]
    [
    false,false,false,
    false,false,false,
    'X','X','X']
    [
    'X',false,false,
    'X',false,false,
    'X',false,false]
    [
    false,'X',false,
    false,'X',false,
    false,'X',false]
    [
    false,false,'X',
    false,false,'X',
    false,false,'X']
    [
    'X',false,false,
    false,'X',false,
    false,false,'X']
    [
    false,false,'X',
    false,'X',false,
    'X',false,false]
    [
    'O','O','O',
    false,false,false,
    false,false,false]
    [
    false,false,false,
    'O','O','O',
    false,false,false]
    [
    false,false,false,
    false,false,false,
    'O','O','O']
    [
    false,false,false,
    false,false,false,
    false,false,false]
    [
    'O',false,false,
    'O',false,false,
    'O',false,false]
    [
    false,'O',false,
    false,'O',false,
    false,'O',false]
    [
    false,false,'O',
    false,false,'O',
    false,false,'O']
    [
    'O',false,false,
    false,'O',false,
    false,false,'O']
    [
    false,false,'O',
    false,'O',false,
    'O',false,false]

end
